// Writes package.json's version into src/version.ts.
// Runs automatically from the "version" lifecycle script (npm version <bump>).
import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const target = new URL("../src/version.ts", import.meta.url);
const content = `// Generated by scripts/sync-version.mjs from package.json. Do not edit.\nexport const version = "${pkg.version}";\n`;

writeFileSync(target, content);
console.log(`src/version.ts -> ${pkg.version}`);
