name: Update GitHub Pages Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-pages-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Update gh-pages branch
        run: |
          # Switch to gh-pages branch or create it if it doesn't exist
          git checkout gh-pages || git checkout -b gh-pages
          
          # Reset gh-pages to match main (this will update all files)
          git reset --hard main
          
          # Push the updated gh-pages branch
          git push origin gh-pages --force
